export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAIL = 'USER_GET_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const NODE_CHECK_REQUEST = 'NODE_CHECK_REQUEST';
export const NODE_CHECK_SUCCESS = 'NODE_CHECK_SUCCESS';
export const NODE_CHECK_FAIL = 'NODE_CHECK_FAIL';

export const PRT_CHECK_REQUEST = 'PRT_CHECK_REQUEST';
export const PRT_CHECK_SUCCESS = 'PRT_CHECK_SUCCESS';
export const PRT_CHECK_FAIL = 'PRT_CHECK_FAIL';

export const ALARM_CHECK_REQUEST = 'ALARM_CHECK_REQUEST';
export const ALARM_CHECK_SUCCESS = 'ALARM_CHECK_SUCCESS';
export const ALARM_CHECK_FAIL = 'ALARM_CHECK_FAIL';

export const ALARM_FILTER_CHECK_REQUEST = 'ALARM_FILTER_CHECK_REQUEST';
export const ALARM_FILTER_CHECK_SUCCESS = 'ALARM_FILTER_CHECK_SUCCESS';
export const ALARM_FILTER_CHECK_FAIL = 'ALARM_FILTER_CHECK_FAIL';

export const ALARM_FILTER_ADD_REQUEST = 'ALARM_FILTER_ADD_REQUEST';
export const ALARM_FILTER_ADD_SUCCESS = 'ALARM_FILTER_ADD_SUCCESS';
export const ALARM_FILTER_ADD_FAIL = 'ALARM_FILTER_ADD_FAIL';

export const ALARM_FILTER_UPDATE_REQUEST = 'ALARM_FILTER_UPDATE_REQUEST';
export const ALARM_FILTER_UPDATE_SUCCESS = 'ALARM_FILTER_UPDATE_SUCCESS';
export const ALARM_FILTER_UPDATE_FAIL = 'ALARM_FILTER_UPDATE_FAIL';

export const HELP_ADD_REQUEST = 'HELP_ADD_REQUEST';
export const HELP_ADD_SUCCESS = 'HELP_ADD_SUCCESS';
export const HELP_ADD_FAIL = 'HELP_ADD_FAIL';

export const HELP_GET_REQUEST = 'HELP_GET_REQUEST';
export const HELP_GET_SUCCESS = 'HELP_GET_SUCCESS';
export const HELP_GET_FAIL = 'HELP_GET_FAIL';

export const HELP_UPDATE_REQUEST = 'HELP_UPDATE_REQUEST';
export const HELP_UPDATE_SUCCESS = 'HELP_UPDATE_SUCCESS';
export const HELP_UPDATE_FAIL = 'HELP_UPDATE_FAIL';

export const HELP_DELETE_REQUEST = 'HELP_DELETE_REQUEST';
export const HELP_DELETE_SUCCESS = 'HELP_DELETE_SUCCESS';
export const HELP_DELETE_FAIL = 'HELP_DELETE_FAIL';
